title: "Debugå®¢æ ˆ"
languageCode: "zh-CN"
baseurl: "debuginn.cn"
theme: "MDgo"
MetaDataFormat: "yaml"
Copyright: "é²ICPå¤‡18012789å·"
# canonifyurls: true
builddrafts: false
PaginatePath: paginator
pygmentsStyle: "default"
pygmentsUseClasses: true
disablePathToLower: true
hasCJKLanguage: true
permalinks:
  posts: /:year/:month/:day/:slug/

outputs:
  home:
    - "HTML"
    # - "RSS"

# outputFormats:
#   RSS:
#     mediatype: "application/rss"
#     baseName: "feed"

Taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"

author:
  name: "debuginn"

params:
  UserName: "Mengå°ç¾½"
  UserGitHub: "debuginn"
  UserEmail: "debuginn@icloud.com"
  UserTelegram: "debuginn"
  DateForm: "2020å¹´07æœˆ26æ—¥ 15:04:05"
  sidebarrecentlimit: 5
  Tagline: "thinking"
  Description: "åšä¸€ä¸ªçˆ±åˆ†äº«çš„ç¨‹åºçŒ¿"
  Keywords: "ç‹¬ç«‹åšå®¢,ç¨‹åºå‘˜,æ€è€ƒ,è¯»ä¹¦ç¬”è®°,æŠ€æœ¯åˆ†äº«"
  NoticeText: "MDgo - åŸºäº Hugo é™æ€æ­å»ºï¼ŒMDUI è®¾è®¡çš„ç±» Github
  é£æ ¼åšå®¢ä¸»é¢˜ï¼Œæ¬¢è¿ä½ å¯¹æ­¤ä¸»é¢˜æäº¤ä½ çš„å»ºè®®ï¼Œè¯·ç‚¹å‡»å³ä¾§æŒ‰é’®"
  NoticeLink: "https://github.com/debuginn/MDgo/issues"
  Info: "å“å‘€ (Â´///Ï‰///`) è¢«å‘ç°æƒ¹ï¼<br />ğŸ¤  &nbsp;åšä¸€ä¸ªçˆ±åˆ†äº«çš„ç¨‹åºçŒ¿<br />çƒ­çˆ±å¼€æºï¼Œçƒ­çˆ±æŠ€æœ¯ï¼Œåˆ†äº«çŸ¥è¯†ï¼Œäº¤æµç»éªŒ"
  FooterContent: "è®¢é˜…æœ¬ç«™ / èµåŠ©æœ¬ç«™ / å¹¿å‘Šåˆä½œ / ä½¿ç”¨è¯´æ˜ / å…³äºç«™é•¿ / å‹æƒ…é“¾æ¥"
  baidu_verification: ""
  google_verification: ""
  

menu:
  main:
      - Name: "æŠ€æœ¯å½’æ¡£"
        Weight: -3
        URL: "/skill/"
      - Name: "ç§‘æŠ€æ‚è°ˆ"
        Weight: -3
        URL: "/think/"
      - Name: "å…³äºæˆ‘"
        Weight: -1
        URL: "/about/"

images:
  - 480x
  - 768x
  - 960x
  - 1024x
  - 1920x
  - 720x340
  - 520x245
